name: My first Workflow

on:
  workflow_dispatch:
  
jobs:
  first-steps:
    runs-on: [ ubuntu-latest ]
    name: my first job
    steps:
      - name: Greet the humans!
        run: |
          echo "Welcome Human.... I come in peace..."
